version: "3.5"

services:
  api01: &api
    image: mateuxlucax/rinha-de-backend-2024-q1-kotlin:latest
    container_name: api01
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "250MB"

networks:
  rinha-network: