name: rinha_de_backend_2024_q1_dart
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.0
  postgres: ^3.0.8

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
