version: "3.5"

services:
  rinha-db:
    container_name: rinha-db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/script.sql
      - ./data/db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"

  rinha-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rinha-pgadmin
    restart: unless-stopped
    depends_on:
      - rinha-db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
