version: "3.5"

services:
  rinha-db:
    container_name: rinha-db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    restart: unless-stopped
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "fsync=off" ]
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
