name: Build and Deploy Dart Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Build and Deploy Dartify Application"
        name: Checkout
        uses: actions/checkout@v3
        working-directory: ./dart

      - run: echo "Setting up Docker"
        name: Login to Docker Hub
        uses: docker/login-action@v3
        working-directory: ./dart
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "Building and Pushing Docker Image"
        name: Build and push
        uses: docker/build-push-action@v5
        working-directory: ./dart
        with:
          context: .
          push: true
          tags: mateuxlucax/rinha-de-backend-2024-q1:dart