name: Build and Deploy Quarkus Application - Native

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:kotlin"
          push: true
          tags: mateuxlucax/rinha-de-backend-2024-q1:quarkus