name: Build and Deploy Quarkus Application - Native

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        
      - uses: actions/setup-java@v4
        name: Set up Java
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Quarkus Application
        working-directory: ./kotlin
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to Docker Hub
        uses: docker/build-push-action@v5
        working-directory: ./kotlin
        with:
          context: "{{defaultContext}}:kotlin"
          file: ./Dockerfile.native-micro
          push: true
          tags: mateuxlucax/rinha-de-backend-2024-q1:quarkus